apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: storageos-etcd
  name: storageos-etcd
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: metrics
  jobLabel: storageos-etcd
  namespaceSelector:
    matchNames:
    - storageos
  selector:
    matchLabels:
      app: etcd
