---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: default
  labels:
    app: jenkins
spec:
  ports:
    - port: 50000
      targetPort: 50000
      name: slavelistener
  selector:
    app: jenkins
    component: jenkins-master
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
  labels:
    app: jenkins
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: jenkins
    component: jenkins-master
  type: ClusterIP
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jenkins-nodeport
#  namespace: default
#  labels:
#    app: jenkins
#spec:
#  ports:
#    - port: 8080
#      name: http
#      targetPort: 8080
#      nodePort: 30000
#  selector:
#    app: jenkins
#    component: jenkins-master
#  type: NodePort
#---
