apiVersion: v1
kind: Endpoints
metadata:
  name: etcd
  namespace: storageos
  labels:
    app: etcd
subsets:
  - addresses:
      - ip: 10.1.10.202
    ports:
    - name: metrics
      port: 2379
      protocol: TCP
