# Only available with CSI installation 
# K8S version >= 1.10 with csi enabled

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageos
parameters:
  fsType: ext4
  pool: default
  storageos.com/replicas: "1"
provisioner: storageos
